FROM avogadro12-base

WORKDIR /avogadro
RUN cmake .
RUN make -j4 && make install
RUN sudo make install

ENV USERNAME avogadro
RUN useradd -m $USERNAME \
 && echo "$USERNAME:$USERNAME" | chpasswd \
 && usermod --shell /bin/bash $USERNAME \
 && usermod -aG sudo $USERNAME \
 && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME \
 && chmod 0440 /etc/sudoers.d/$USERNAME \
 && usermod  --uid 1000 $USERNAME \
 && groupmod --gid 1000 $USERNAME

USER $USERNAME
ENTRYPOINT ["/usr/local/bin/avogadro"]
